# Generated by Django 5.0.7 on 2024-07-10 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales_network.contact', verbose_name='Контактная информация'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_network',
            field=models.ManyToManyField(to='sales_network.network', verbose_name='Реализаторы'),
        ),
    ]
