# Generated by Django 5.0.7 on 2024-07-10 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0002_alter_network_contact_alter_product_name_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_network.network', verbose_name='Поставщик'),
        ),
    ]
